### ISSUE TITLE
Support ROS2 Bundles

### ISSUE THREAD

**Issue by ryanewel** [colcon/colcon-ros-bundle#14]
I'd like to be able to bundle ROS2 applications with colcon bundle. When I tried it today I got the following error:

```
root@c3ecc06d90eb:/ws# colcon bundle
Bundling workspace...
Reading package lists... Done
Building dependency tree... Done
Checking if dependency tarball exists...
Collecting dependency information...
[62.786s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[62.984s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[63.162s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_python package
[63.335s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[63.475s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[63.616s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
                      
Summary: 0 packages finished [57.6s]
Fetching and installing dependencies...
[81.748s] ERROR:colcon:colcon bundle: [Errno 2] No such file or directory: '/ws/bundle/bundle_staging/setup.sh'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/colcon_core/command.py", line 436, in verb_main
    rc = context.args.main(context=context)
  File "/usr/local/lib/python3.5/dist-packages/colcon_bundle/verb/bundle.py", line 129, in main
    generate_archive_v1(path_context)
  File "/usr/local/lib/python3.5/dist-packages/colcon_bundle/verb/_archive_generators.py", line 29, in generate_archive_v1
    shutil.copy2(shellscript_path, os.path.join(staging_path, 'setup.sh'))
  File "/usr/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/ws/bundle/bundle_staging/setup.sh'
```

**Comment by murphm8** [comment]
In order to support ROS2 we will need a bundle task implementation for `ros.ament_cmake` and `ros.ament_python`. Since these types still use `package.xml` I don't think it will be too hard. We need to make sure whichever package identifies these types is adding all the metadata we need to the `PackageDescriptor`.

**Comment by murphm8** [comment]
From that error message it looks like you're trying to generate a V1 archive. ROS2D only supports V2. 

`generate_archive_v1(path_context)`

**Comment by timrobotson** [comment]
I'm seeing these same warnings with the latest version of colcon + bundle when bundling https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch with ROS2:

```
root@b3e261bf8a32:/opt/workspace/simulation_ws# colcon bundle
Bundling workspace...
Reading package lists... Done
Building dependency tree... Done
Checking if dependency tarball exists...
[12.919s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[12.926s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_python package
[12.932s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[12.939s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[12.946s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[12.953s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[12.959s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[12.967s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[12.977s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[12.988s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_python package
[12.999s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_python package
[13.012s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[13.023s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[13.035s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[13.047s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[13.058s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[13.067s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_cmake package
[13.074s] WARNING:colcon.colcon_bundle.verb:No task extension to bundle a ros.ament_python package
                      
Summary: 0 packages finished [12.6s]
Collecting dependency information...
Fetching and installing dependencies...
Creating bundle archive V2...
```

Colcon versions:
```
root@b3e261bf8a32:/opt/workspace/simulation_ws# pip list | grep colcon
colcon-argcomplete              0.3.3      
colcon-bash                     0.4.0      
colcon-bundle                   0.0.16     
colcon-cmake                    0.2.13     
colcon-common-extensions        0.2.0      
colcon-core                     0.4.0      
colcon-defaults                 0.2.2      
colcon-devtools                 0.2.1      
colcon-library-path             0.2.1      
colcon-metadata                 0.2.2      
colcon-notification             0.2.9      
colcon-output                   0.2.4      
colcon-package-information      0.2.3      
colcon-package-selection        0.2.5      
colcon-parallel-executor        0.2.4      
colcon-pkg-config               0.1.0      
colcon-powershell               0.3.4      
colcon-python-setup-py          0.2.2      
colcon-recursive-crawl          0.2.0      
colcon-ros                      0.3.11     
colcon-ros-bundle               0.0.11     
colcon-test-result              0.3.5      
colcon-zsh                      0.4.0   
```

With ubuntu 18.04 bionic + ROS Dashing in a docker container.

**Comment by murphm8** [comment]
ROS2D support has been released in the latest version of `colcon-bundle` and `colcon-ros-bundle`
